services:

  postgres_base:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - services
