"""migration2

Revision ID: 98498957e218
Revises: a71fab5587ae
Create Date: 2024-05-07 01:56:43.093085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98498957e218"
down_revision: str | None = "a71fab5587ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_accounts",
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("social_id", sa.String(length=255), nullable=False),
        sa.Column("social_name", sa.String(length=255), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_unique_constraint(None, "login_history", ["uuid"])
    op.create_unique_constraint(None, "permissions", ["uuid"])
    op.create_unique_constraint(None, "roles", ["uuid"])
    op.create_unique_constraint(None, "roles_permissions", ["uuid"])
    op.create_unique_constraint(None, "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "roles_permissions", type_="unique")
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_constraint(None, "permissions", type_="unique")
    op.drop_constraint(None, "login_history", type_="unique")
    op.drop_table("social_accounts")
    # ### end Alembic commands ###
